In [49]:
import numpy as np
from scipy import linalg, sparse

In [46]:
A = np.matrix(np.matrix(np.random.random((2,2))))
b = np.random.random((2,2))
B = np.asmatrix(b)#배열을 행렬로 전환
C = np.mat(np.random.random((10,5)))
D = np.mat([[3,4],[5,6]])
print(B)
print(C)
print(D)

[[0.95063602 0.40116021]
 [0.07666981 0.04488607]]
[[0.48837894 0.47790494 0.20095211 0.63657556 0.93853358]
 [0.76660831 0.21742257 0.20365505 0.10532478 0.12316014]
 [0.62067104 0.81494454 0.5168571  0.44114427 0.38966334]
 [0.66801328 0.97987371 0.84574605 0.21278484 0.99407476]
 [0.48948848 0.35312432 0.46581047 0.39526257 0.93948626]
 [0.63106884 0.63700445 0.36157407 0.04509971 0.30251162]
 [0.26743928 0.95180391 0.0264598  0.68713951 0.56054521]
 [0.96698034 0.82897179 0.11527103 0.87872595 0.0261857 ]
 [0.02070836 0.68809734 0.91885143 0.35487559 0.79132937]
 [0.1001188  0.49912598 0.77543761 0.13049584 0.10902222]]
[[3 4]
 [5 6]]


In [48]:
#A의 역행렬
A.I

matrix([[ 3.89103904, -2.56088905],
        [-2.53870786,  2.87363241]])

In [51]:
#A의 행렬식
linalg.det(A)

0.21367216735964215

In [53]:
#A의 전치행렬
A.T

matrix([[0.61401526, 0.54245121],
        [0.54719071, 0.83140674]])

In [60]:
#A의 연산
np.add(A, D)
np.subtract(A, D)
#행렬곱
print(D@B)
print(np.dot(D, B))
#대응되는 원소끼리 단순 곱셉
print(np.multiply(D, B))

[[3.15858729 1.38302492]
 [5.21319895 2.27511749]]
[[3.15858729 1.38302492]
 [5.21319895 2.27511749]]
[[2.85190806 1.60464085]
 [0.38334904 0.26931642]]


In [62]:
#2X2 항등행렬
G = np.mat(np.identity(2))
G

matrix([[1., 0.],
        [0., 1.]])